/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StocktakeRouteImport } from './routes/stocktake'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OutboundRouteImport } from './routes/outbound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as FirstTimeSetupRouteImport } from './routes/first-time-setup'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutboundPaymentReceiptIdRouteImport } from './routes/outbound-payment/$receiptId'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StocktakeRoute = StocktakeRouteImport.update({
  id: '/stocktake',
  path: '/stocktake',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundRoute = OutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstTimeSetupRoute = FirstTimeSetupRouteImport.update({
  id: '/first-time-setup',
  path: '/first-time-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundPaymentReceiptIdRoute =
  OutboundPaymentReceiptIdRouteImport.update({
    id: '/outbound-payment/$receiptId',
    path: '/outbound-payment/$receiptId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/feedback': typeof FeedbackRoute
  '/first-time-setup': typeof FirstTimeSetupRoute
  '/inbound': typeof InboundRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/outbound': typeof OutboundRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/stocktake': typeof StocktakeRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/tracking': typeof TrackingRoute
  '/transfer': typeof TransferRoute
  '/outbound-payment/$receiptId': typeof OutboundPaymentReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/feedback': typeof FeedbackRoute
  '/first-time-setup': typeof FirstTimeSetupRoute
  '/inbound': typeof InboundRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/outbound': typeof OutboundRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/stocktake': typeof StocktakeRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/tracking': typeof TrackingRoute
  '/transfer': typeof TransferRoute
  '/outbound-payment/$receiptId': typeof OutboundPaymentReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/feedback': typeof FeedbackRoute
  '/first-time-setup': typeof FirstTimeSetupRoute
  '/inbound': typeof InboundRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/outbound': typeof OutboundRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/stocktake': typeof StocktakeRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/tracking': typeof TrackingRoute
  '/transfer': typeof TransferRoute
  '/outbound-payment/$receiptId': typeof OutboundPaymentReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/feedback'
    | '/first-time-setup'
    | '/inbound'
    | '/location'
    | '/login'
    | '/outbound'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register'
    | '/settings'
    | '/staff'
    | '/stocktake'
    | '/suppliers'
    | '/terms'
    | '/tracking'
    | '/transfer'
    | '/outbound-payment/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/feedback'
    | '/first-time-setup'
    | '/inbound'
    | '/location'
    | '/login'
    | '/outbound'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register'
    | '/settings'
    | '/staff'
    | '/stocktake'
    | '/suppliers'
    | '/terms'
    | '/tracking'
    | '/transfer'
    | '/outbound-payment/$receiptId'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/feedback'
    | '/first-time-setup'
    | '/inbound'
    | '/location'
    | '/login'
    | '/outbound'
    | '/privacy'
    | '/products'
    | '/profile'
    | '/register'
    | '/settings'
    | '/staff'
    | '/stocktake'
    | '/suppliers'
    | '/terms'
    | '/tracking'
    | '/transfer'
    | '/outbound-payment/$receiptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  FeedbackRoute: typeof FeedbackRoute
  FirstTimeSetupRoute: typeof FirstTimeSetupRoute
  InboundRoute: typeof InboundRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  OutboundRoute: typeof OutboundRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StocktakeRoute: typeof StocktakeRoute
  SuppliersRoute: typeof SuppliersRoute
  TermsRoute: typeof TermsRoute
  TrackingRoute: typeof TrackingRoute
  TransferRoute: typeof TransferRoute
  OutboundPaymentReceiptIdRoute: typeof OutboundPaymentReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocktake': {
      id: '/stocktake'
      path: '/stocktake'
      fullPath: '/stocktake'
      preLoaderRoute: typeof StocktakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound': {
      id: '/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof OutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-time-setup': {
      id: '/first-time-setup'
      path: '/first-time-setup'
      fullPath: '/first-time-setup'
      preLoaderRoute: typeof FirstTimeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound-payment/$receiptId': {
      id: '/outbound-payment/$receiptId'
      path: '/outbound-payment/$receiptId'
      fullPath: '/outbound-payment/$receiptId'
      preLoaderRoute: typeof OutboundPaymentReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  FeedbackRoute: FeedbackRoute,
  FirstTimeSetupRoute: FirstTimeSetupRoute,
  InboundRoute: InboundRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  OutboundRoute: OutboundRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StocktakeRoute: StocktakeRoute,
  SuppliersRoute: SuppliersRoute,
  TermsRoute: TermsRoute,
  TrackingRoute: TrackingRoute,
  TransferRoute: TransferRoute,
  OutboundPaymentReceiptIdRoute: OutboundPaymentReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
